name: 'Python Lint'

on: 
  push:
    branches:
      - dev
      - "release*"
    tags:
      - '*'
  pull_request:

jobs:
  lint_python:
    runs-on: ubuntu-latest
    steps:
      - name: 'Cleanup workspace'
        uses: AutoModality/action-clean@v1

      - name: 'Checkout code'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Setup python'
        uses: actions/setup-python@v2

      - name: 'Check python code with black'
        uses: psf/black@20.8b1
